### ISSUE TITLE
image chrome tab error

### ISSUE THREAD

**Issue by robertovaldesperez** [caioproiete/hangfire-dashboard-customize#2]
app.UseHangfireDashboardCustomOptions(new HangfireDashboardCustomOptions
            {
                DashboardTitle = () => "<img style=\"display: inline !important; margin-top: -7px;\" src=\"/images/logo.png\" /> <b>Titulo</b>"
            });
![image](https://user-images.githubusercontent.com/15571467/105866559-68cf3100-5ff4-11eb-8ad7-912058b477d7.png)

**Comment by augustoproiete** [comment]
Thanks for reporting @robertovaldesperez Looks like we need to [adjust the Regex](https://github.com/augustoproiete/hangfire-dashboard-customize/blob/master/src/Hangfire.Dashboard.Customize/HangfireDashboardCustomOptionsMiddleware.cs#L25) so that it skips the title header.

Let me know if this is something you're keen to send a PR to fix, otherwise I'll take a look over the weekend.

**Comment by robertovaldesperez** [comment]
Don't worry,  I'm not in a hurry, check it out on the weekend if you can. Thanks a lot @augustoproiete

**Comment by augustoproiete** [comment]
@robertovaldesperez I've just published [Hangfire.Dashboard.Customize v1.1.0-preview](https://www.nuget.org/packages/Hangfire.Dashboard.Customize/1.1.0-preview) which should fix the issue you reported and allow a little more control over the title replacement.

When doing the replacement of the `DashboardTitle` I make sure to skip to the HTML `<body>` first to ensure the title you see on the browser tab is not replaced with the contents of your `DashboardTitle` property (where you can have the image as in your example).

I also introduced a new property called `BrowserTitle` (optional) which allows you to replace the title you see in the browser tab separately. This allows you to have a one title in the browser tab (no images) and another in the nav bar (with or without images).

The configuration code looks like this:

```csproj
app.UseHangfireDashboardCustomOptions(new HangfireDashboardCustomOptions
{
    BrowserTitle = () => "Titulo",
    DashboardTitle = () => "<img style=\"display: inline !important; margin-top: -7px;\" src=\"/images/logo.png\" /> Titulo",
});
```

e.g.

![image](https://user-images.githubusercontent.com/177608/106549104-aa754580-64e6-11eb-9d9e-18225a6534a0.png)

If you have a chance, please take it for a spin and let me know if this fixes and/or if you see any other issue.

```xml
<PackageReference Include="Hangfire.Dashboard.Customize" Version="1.1.0-preview" />
```

If everything works, I'll release version 1.1.0 RTM later this week.

**Comment by robertovaldesperez** [comment]
It works very well, thank you very much @augustoproiete.

![image](https://user-images.githubusercontent.com/15571467/106585233-66fef380-6547-11eb-80d2-4e9f5e6924ee.png)

Is it possible to customize the icon of the browser tab? It would be great to be able to customize the image of the browser tab

**Comment by augustoproiete** [comment]
@robertovaldesperez Great!

As for the icon of the browser tab, we need a slightly different approach because the Hangfire Dashboard doesn't define a link tag, so it's not a 1:1 replacement like the title is.

I've just published [Hangfire.Dashboard.Customize v1.1.0-preview2](https://www.nuget.org/packages/Hangfire.Dashboard.Customize/1.1.0-preview), which adds a couple more optional properties: `AppendToHead` and `AppendToBody`.

- `AppendToHead` allows you to inject any content just before `</head>` tag - this gives you the ability to, for example, add icons, or perhaps load other CSS files to override existing styles.

- `AppendToBody` allows you to inject any content just before the `</body>` tag - this gives you the ability to, for example, load other javascript files.

```csharp
app.UseHangfireDashboardCustomOptions(new HangfireDashboardCustomOptions
{
    BrowserTitle = () => "Titulo",
    DashboardTitle = () => "<img style=\"display: inline !important; margin-top: -7px;\" src=\"/images/logo.png\" /> Titulo",

    AppendToHead = () => "<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/favicon.ico\" />",
});
```

![image](https://user-images.githubusercontent.com/177608/106678318-d6e59c00-6590-11eb-9370-a3d088715859.png)

As before, if you have a chance, please take it for a spin and let me know if this works.

```xml
<PackageReference Include="Hangfire.Dashboard.Customize" Version="1.1.0-preview2" />
```

Again, if everything works, I'll release version 1.1.0 RTM later this week.

**Comment by robertovaldesperez** [comment]
It works very well, thank you very much @augustoproiete.

![image](https://user-images.githubusercontent.com/15571467/106870245-2cc15d80-66d1-11eb-9a66-2c835f7cebe5.png)
